### PR TITLE
Turn loadmore into a property instead of a reply

### PR DESCRIPTION
**Pull request by ajacksified**
👓 @schwers

### CODE REVIEW

**Comment by curioussavage** [comment]
why do we commit the bundle with webpack?

**Comment by schwers** [comment]
@curioussavage it's nicer for anyone who isn't using webpack in their stack, and it makes having `npm link`'ed modules easier to develop as there's no need to resolve plugins. Still looking into the right way to build only the parts your reddit project needs

**Comment by schwers** [comment]
:fish:

**Comment by curioussavage** [comment]
kool

**Pull request merged**
