### PR TITLE
add autocomplete endpoint

### PR DESCRIPTION
**Pull request by phil303**
- I've also update the nomenclature of `save` to `runForm`
since this is more accurately what it does. Eventually I'm
going to refactor and clean these functions up anyway.

### CODE REVIEW

**Comment by phil303** [comment]
:eyeglasses: @schwers

**Comment by uzi** [comment]
:fish: looks fine to me once CI is happy

**Comment by phil303** [comment]
@uzi I'm starting to think our CI is never happy :(

**Comment by schwers** [comment]
I'm surprised the cli is complaining about `superagent-retry`, once that's fixed it will probably still complain about the linter issues anyway. :/ :fish:

**Pull request merged**
